name: b_music02
description: B_music02 müzik topluluğu mobil uygulaması
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  http: ^1.2.2
  supabase_flutter: ^2.0.0
  video_player: ^2.9.2
  webview_flutter: 4.12.0
  webview_flutter_android: 4.10.1
  share_plus: ^12.0.2

  # Müzik oynatma
  just_audio: ^0.10.6

  # Arka plan + bildirim + kilit ekranı
  audio_service: ^0.18.19
  audio_session: ^0.2.2

  # Telefondaki müzikleri otomatik bul
  on_audio_query: ^2.9.0

  # Android bildirim izni
  permission_handler: ^12.0.1

  # Yerel dosyalar
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/b_music02_logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/images/b_music02_logo.png
  adaptive_icon_background: '#0B0B0B'
  adaptive_icon_foreground: assets/images/b_music02_logo.png

